### ISSUE TITLE
How to mesh with @electron-forge/publisher-snapcraft?

### ISSUE THREAD

**Issue by michaelfig** [davidwinter/electron-forge-maker-snap#38]
I'm trying to publish my built snap to snapcraft, and I'm getting this:
```
yarn run v1.22.10
$ electron-forge publish --from-dry-run
✔ Checking your system
✔ Resolving publish target: @electron-forge/publisher-github
✔ Searching for target release: 0.2.1
✔ Uploading Artifacts 2/2 to v0.2.1
✔ Resolving publish target: @electron-forge/publisher-snapcraft
✖ Pushing snap to the snap store

An unhandled error has occurred inside Forge:
The "file" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at Object.spawn (child_process.js:547:16)
    at Object.spawn [as default] (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@malept/cross-spawn-promise/node_modules/cross-spawn/index.js:12:24)
    at /home/mfig/Pledger-lin/packages/app-electron/node_modules/@malept/cross-spawn-promise/src/index.ts:135:31
    at new Promise (<anonymous>)
    at spawn (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@malept/cross-spawn-promise/src/index.ts:132:10)
    at Snapcraft.run (/home/mfig/Pledger-lin/packages/app-electron/node_modules/electron-installer-snap/src/snapcraft.js:94:14)
    at asyncFn (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/publisher-snapcraft/src/PublisherSnapcraft.ts:35:23)
    at /home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/publisher-snapcraft/node_modules/@electron-forge/async-ora/src/ora-handler.ts:35:5
    at new Promise (<anonymous>)
    at asyncOra (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/publisher-snapcraft/node_modules/@electron-forge/async-ora/src/ora-handler.ts:34:10)
    at PublisherSnapcraft.publish (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/publisher-snapcraft/src/PublisherSnapcraft.ts:33:11)
    at publish (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/core/src/api/publish.ts:180:5)
    at publish (/home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/core/src/api/publish.ts:92:7)
    at /home/mfig/Pledger-lin/packages/app-electron/node_modules/@electron-forge/cli/src/electron-forge-publish.ts:36:3
error Command failed with exit code 1.
```

Here are the relevant config files: https://gist.github.com/michaelfig/187ec5f3edeb3a8afbede5fbd0537fac

Just wondering anybody here uses the electron forge snapcraft publisher?

Thanks.

**Comment by arthyn** [comment]
I'd like to do the same, @michaelfig did you end up just manually publishing?

**Comment by michaelfig** [comment]
> I'd like to do the same, @michaelfig did you end up just manually publishing?

Yeah, basically, with parts of my `package.json` like this:

```json
  "scripts": {
    "publish:electron": "electron-forge publish"
  },
   
      "makers": [
        {
          "name": "@davidwinter/electron-forge-maker-snap",
          "oldname": "@electron-forge/maker-snap",
          "config": {
            "name": "pledger",
            "confinement": "strict",
            "executableName": "pledger"
          }
        }
      ]
```

And several other makers and publishers, but no Snapcraft publisher.  Then from CI/CD:

```sh
        SNAPCRAFT_BUILD_ENVIRONMENT=host yarn publish:electron --dry-run
        yarn publish:electron --from-dry-run
        echo "$SNAPCRAFT_TOKEN" | snapcraft login --with -
        snapcraft upload --release=$release out/make/*.snap
```

**Comment by davidwinter** [comment]
@michaelfig @arthyn apologies for the delay in responding, I've not been receiving GitHub issue notifications for some reason! :grimacing: 

I just wanted to check, is there a reason for running the command twice, first with `--dry-run` and then with `--from-dry-run`?

And are you using the `make` command before that to generate the snap file?

**Comment by michaelfig** [comment]
> @michaelfig @arthyn apologies for the delay in responding, I've not been receiving GitHub issue notifications for some reason! 😬

No worries!  I mostly wanted to post here to let others know what could be done since I managed to work around the issue.  Thanks for getting back, though.

> I just wanted to check, is there a reason for running the command twice, first with `--dry-run` and then with `--from-dry-run`?

My only reason is that when the `publish:electron` sometimes would fail due to network connectivity, the `--from-dry-run` would be a way to quickly retry rather than running everything again.

> And are you using the `make` command before that to generate the snap file?

`yarn publish:electron --dry-run` above automatically does an `electron-forge make` as part of its normal process, AFAICT.

**Comment by davidwinter** [comment]
From what I can see in the `.publish` file, the artifacts are being persisted correctly in the publish dry run (`{"artifacts":["out/make/pledger-0.2.1.snap"]...`) so this might be an issue with `electron-installer-snap` package which is used under the hood by the `electron-forge` snap publisher to handle the `snapcraft` command. It might be outdated or broken like the original maker (the reason I wrote this package in the first place) so it may be that the way you're doing it is the best and most up-to-date. I'm not so sure it's an issue with this package I'm afraid.
